name: Build executables

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: |
          python3 .\releases\compiler\compiler.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backup_helper-${{ matrix.os }}
          path: dist/backup_helper*